#!/usr/bin/env ruby

require "pp"
require "ripper"
require "iripper"

DELIM_RE = /[[:space:]]+/
BLANK_RE = /\A[[:space:]]*\z/

def show_version
  puts IRipper::VERSION
end

def show_help
  puts "TODO: Show help"
end

default = ARGV[0] ? ARGV[0].strip : nil

case default
when "help"
  show_help
  exit
when "version"
  show_version
  exit
end

loop do
  if default
    print "iripper(#{default})> "
  else
    print "iripper> "
  end

  begin
    line = $stdin.gets.chomp
  rescue NoMethodError, Interrupt
    exit
  end

  cmd, src = line.split(DELIM_RE, 2)
  case cmd
  when "default"
    if BLANK_RE.match?(src)
      default = nil
    else
      default = src.strip
    end
    next
  when "help"
    show_help
    next
  when "version"
    show_version
    next
  when "exit", "quit"
    exit
  end

  if default
    cmd, src = default, line
  end

  case cmd
  when "lex"
    pp Ripper.lex(src)
    next
  when "parse"
    pp Ripper.parse(src)
    next
  when "sexp"
    pp Ripper.sexp(src)
    next
  when "tokenize"
    pp Ripper.tokenize(src)
    next
  end

  warn "unknown command: #{cmd}"
end
