#!/usr/bin/env ruby

require "pp"
require "ripper"
require "iripper"

DELIM_RE = /[[:space:]]+/

default = ARGV[0]

if default
  prompt = "iripper(#{default})> "
else
  prompt = "iripper> "
end

loop do
  print prompt

  begin
    line = $stdin.gets.chomp
  rescue NoMethodError, Interrupt
    exit
  end

  cmd, src = line.split(DELIM_RE, 2)
  case cmd
  when "help"
    puts "TODO: Show help"
    next
  when "version"
    puts IRipper::VERSION
    next
  when "exit", "quit"
    exit
  end

  if default
    cmd, src = default, line
  end

  case cmd
  when "lex"
    pp Ripper.lex(src)
  when "parse"
    pp Ripper.parse(src)
  when "sexp"
    pp Ripper.sexp(src)
  when "tokenize"
    pp Ripper.tokenize(src)
  else
    warn "unknown command: #{cmd}"
  end
end
