#!/usr/bin/env ruby

require "pp"
require "ripper"
require "ripper/repl"

default = ARGV[0]

if default
  prompt = "ripper(#{default})> "
else
  prompt = "ripper> "
end

loop do
  print prompt

  begin
    line = $stdin.gets.chomp
  rescue NoMethodError, Interrupt
    exit
  end

  if default
    cmd, src = default, line
  else
    cmd, src = line.split(/[[:space:]]/, 2)
  end

  case cmd
  when "lex"
    pp Ripper.lex(src)
  when "parse"
    pp Ripper.parse(src)
  when "sexp"
    pp Ripper.sexp(src)
  when "tokenize"
    pp Ripper.tokenize(src)
  when "version"
    puts Ripper::Repl::VERSION
  when "exit", "quit"
    exit
  else
    puts "TODO: Show help"
  end
end
