#!/usr/bin/env ruby

require "pp"
require "ripper"
require "ripper/repl"

loop do
  print "ripper> "
  begin
    line = $stdin.gets.chomp
  rescue NoMethodError, Interrupt
    exit
  end

  cmd, src = line.split(/[[:space:]]/, 2)
  case cmd
  when "lex"
    pp Ripper.lex(src)
  when "parse"
    pp Ripper.parse(src)
  when "sexp"
    pp Ripper.sexp(src)
  when "tokenize"
    pp Ripper.tokenize(src)
  when "version"
    puts Ripper::Repl::VERSION
  when "exit", "quit"
    exit
  else
    puts "TODO: Show help"
  end
end
